"""External stage3 helpers."""

from .api_config import STAGE3_MODELS, STAGE3_RUNTIME_DEFAULTS, slot_payload
from .catalog import ScopeOption, list_available_scope_dirs, list_available_scope_options
from .session import (
    ProposalContext,
    ScopeSelection,
    STAGE3_MANIFEST_FILE,
    STAGE3_SESSION_FILE,
    STAGE3_WORKSPACE_DIR,
    STAGE3_WORKSPACE_MANIFEST_FILE,
    ThemeItem,
    analysis_targets_from_session,
    build_stage3_manifest,
    ensure_stage3_workspace,
    load_stage3_session,
    load_proposal_context,
    manifest_path,
    parse_target_themes_from_proposal,
    reconcile_retrieval_progress,
    resolve_scope_selection,
    save_stage3_session,
    stage3_session_path,
    stage3_workspace_dir,
    stage3_workspace_manifest_path,
    summarize_retrieval_progress,
    update_retrieval_progress,
    update_stage3_session_checkpoint,
    write_stage3_manifest,
)

__all__ = [
    "STAGE3_MODELS",
    "STAGE3_RUNTIME_DEFAULTS",
    "STAGE3_MANIFEST_FILE",
    "STAGE3_SESSION_FILE",
    "STAGE3_WORKSPACE_DIR",
    "STAGE3_WORKSPACE_MANIFEST_FILE",
    "ProposalContext",
    "ScopeSelection",
    "ScopeOption",
    "ThemeItem",
    "analysis_targets_from_session",
    "build_stage3_manifest",
    "ensure_stage3_workspace",
    "list_available_scope_dirs",
    "list_available_scope_options",
    "load_stage3_session",
    "load_proposal_context",
    "manifest_path",
    "parse_target_themes_from_proposal",
    "reconcile_retrieval_progress",
    "resolve_scope_selection",
    "save_stage3_session",
    "slot_payload",
    "stage3_session_path",
    "stage3_workspace_dir",
    "stage3_workspace_manifest_path",
    "summarize_retrieval_progress",
    "update_retrieval_progress",
    "update_stage3_session_checkpoint",
    "write_stage3_manifest",
]
